### ISSUE TITLE
App crasht

### ISSUE THREAD

**Issue by JesperKuipers** [LuukEsselbrugge/SRooster#5]
Na het installeren kan ik hem 1 keer opstarten, want vanaf de 2de keer crash hij bij het opstarten.
Ik gebruik een @stenden account op een up-to-date Samsung Galaxy 10.

**Comment by LuukEsselbrugge** [comment]
Hallo Jesper, dit is een erg raar probleem ik kan het niet zelf reproduceren. Ik zie dat meer mensen hier last van hebben op Android 9. Zelf heb ik ook Android 9 zonder problemen.

Zal je wat meer details kunnen geven over wat je precies invult en je email adres naar mij sturen of hier posten

De app crashed omdat hij probeert de eerste en 2de letter uit je email te halen ik denk dat hier iets fout gaat.

**Comment by LuukEsselbrugge** [comment]
Kan je bij eerste keer opstarten een foto maken van je naam zoals weergegeven in de linkerbovenhoek

**Comment by JesperKuipers** [comment]
Naam.achternaam@student.nhlstenden.com werkt wel maar Sstudentnummer@stenden.com niet

**Comment by LuukEsselbrugge** [comment]
Ah ik wist niet dat het mogelijk is om met student nummer in te loggen. Ik zal dit binnenkort even aanpassen
